module.exports = {
  port:80,
  songs: {
    'Believer': {length: 192,title: "Believer - Imagine Dragons", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Believer.mid"},
    'Boulevard of Broken Dreams': {length: 205 ,title: "Boulevard of Broken Dreams", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Boulevard\ of\ Broken\ Dreams.mid"},
    'Die Forrelle': {length: 95 ,title: "Die Forrelle", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Die\ Forrelle.mid"},
    'Eine Kleine Nachtmusik': {length: 50, title: "Eine Kleine Nachtmusik", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Eine\ Kleine\ Nachtmusik.mid"},
    'Fur Elise': {length: 53, title: "Fur Elise", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Fur\ Elise.mid"},
    'Girl in the Tower': {length: 213, title: "Girl in the Tower", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Girl\ in\ the\ Tower.mid"},
    'Jupiter, the Bringer of Jollity': {length: 60, title: "Jupiter, the Bringer of Jollity", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Jupiter,\ the\ Bringer\ of\ Jollity.mid"},
    'Mario Overworld Theme': {length: 120,title: "Mario Overworld Theme", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Mario\ Overworld\ Theme.mid"},
    'Megalovania': {length: 110,title: "Megalovania", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Megalovania.mid"},
    'Midnas Lament': {length: 104,title: "Midnas Lament", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Midnas\ Lament.mid"},
    'Mozart Variations': {length: 145,title: "Mozart Variations", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Mozart\ Variations.mid"},
    'Ode to Joy': {length: 60,title: "Ode to Joy", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Ode\ to\ Joy.mid"},
    'Phantom of the Opera': {length: 250,title: "Phantom of the Opera", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Phantom\ of\ the\ Opera.mid"},
    'Promenade': {length: 86,title: "Promenade", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Promenade.mid"},
    'Puzzle Battle': {length: 106,title: "Puzzle Battle", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Puzzle_Battle.mid"},
    'Shape of You': {length: 235,title: "Shape of You", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Shape\ of\ You.mid"},
    'Take on Me': {length: 209,title: "Take on Me", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Take\ on\ Me.mid"},
    'Tetris Theme A': {length: 66,title: "Tetris Theme A", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Tetris\ Theme.mid"},
    'The Heritors of Arcadia': {length: 254,title: "The Heritors of Arcadia", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/The\ Heritors\ of\ Arcadia.mid"},
    'The Incredibles Theme': {length: 163,title: "The Incredibles Theme", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/The_Incredibles_.mid"},
    'The Old Castle': {length: 160,title: "The Old Castle", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/The\ Old\ Castle.mid"},
    'Wachet Auf': {length: 227,title: "Wachet Auf", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Wachet\ Auf.mid"},
    'The Can Can': {length: 113, title: "The Can Can", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Can_Can.mid"},
    'Mii Channel': {length: 195, title: "Mii Channel", path: "/home/pi/Midi-Organ/MidiInterpreter/pieces/Mii\ Channel.mid"},
    'Anitra\'s Dance': {length: 200, title:"Anitra\'s Dance", path:"/home/pi/Midi-Organ/MidiInterpreter/pieces/Anitra\'s\ Dance.mid"},
    'Saturn, the Bringer of Old Age':{length: 470, title:"Saturn, the Bringer of Old Age", path:"/home/pi/Midi-Organ/MidiInterpreter/pieces/Saturn,\ the\ Bringer\ of\ Old\ Age.mid"},
    'Morning Mood':{length: 170, title: "Morning Mood",path:"/home/pi/Midi-Organ/MidiInterpreter/pieces/Morning\ Mood.mid"},
    'Ase\'s Death':{length: 215, title: "Ase\'s Death",path:"/home/pi/Midi-Organ/MidiInterpreter/pieces/Ase\'s\ Death.mid"},
    'In the Hall of the Mountain King':{length: 130, title: "In the Hall of the Mountain King",path:"/home/pi/Midi-Organ/MidiInterpreter/pieces/In\ the\ Hall\ of\ the\ Mountain\ King.mid"}
  },
  scriptPath: "/home/pi/Midi-Organ/MidiInterpreter/midiorgan",
  resetPath:  "/home/pi/Midi-Organ/FlushPins/flush"
};
